version: 2
updates:
  # Enable version updates for Ruby dependencies
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "freebeiro"
    labels:
      - "dependencies"
      - "ruby"
    groups:
      development-dependencies:
        dependency-type: "development"
        patterns:
          - "rspec*"
          - "rubocop*"
          - "simplecov*"
      
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    reviewers:
      - "freebeiro"
    labels:
      - "dependencies"
      - "github-actions"