# RuboCop configuration for Dotidot Web Scraper
# This configuration enforces Ruby and Rails best practices

plugins:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'storage/**/*'
    - 'log/**/*'

# Rails specific configuration
Rails:
  Enabled: true

Rails/Blank:
  Exclude:
    - 'app/services/**/*'
    - 'lib/**/*'

# Style configurations
Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Style/StringLiterals:
  EnforcedStyle: double_quotes

# Metrics configurations
Metrics/MethodLength:
  Max: 35

Metrics/ClassLength:
  Max: 150

Metrics/ModuleLength:
  Max: 130

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/routes.rb'

Metrics/AbcSize:
  Max: 30

# Layout configurations
Layout/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'

# Service object pattern support
Style/ClassAndModuleChildren:
  EnforcedStyle: nested

Style/RescueStandardError:
  EnforcedStyle: implicit

# Allow OpenStruct for service responses
Style/OpenStructUse:
  Enabled: false

# Allow hash case statements for error mapping
Style/HashLikeCase:
  Enabled: false

# Allow complexity in specs and service strategies
Metrics/CyclomaticComplexity:
  Exclude:
    - 'spec/**/*'
    - 'app/services/*_strategy.rb'

Metrics/PerceivedComplexity:
  Exclude:
    - 'spec/**/*'
    - 'app/services/*_strategy.rb'