name: Security Checks

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0' # Weekly on Sunday

jobs:
  security:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2.6'
        bundler-cache: true
    
    - name: Run Brakeman security scanner
      run: |
        gem install brakeman
        brakeman -A -z -q
    
    - name: Check for known vulnerabilities in dependencies
      run: |
        gem install bundler-audit
        rm -rf ~/.local/share/ruby-advisory-db
        bundle audit check --update
    
    - name: Check for hardcoded secrets
      run: |
        # Check for sensitive data patterns in Ruby files
        echo "Checking for hardcoded secrets..."
        if grep -r --include="*.rb" --include="*.yml" --include="*.yaml" -E "(password|secret|key|token)\s*[:=]\s*['\"][^'\"]+['\"]" app config lib 2>/dev/null; then
          echo "WARNING: Potential hardcoded secrets found. Please review."
          exit 1
        else
          echo "✓ No hardcoded secrets found"
        fi